---
title: Mago Analytics
timezone: Etc/UTC
collections:
  posts:
    title: Posts
    output: true
  staff_members:
    title: Staff Members
    output: false
    _hide_content: true
    _icon: account_circle
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    _options:
      image_path:
        width: 440
        height: 440
        uploads_dir: "/images/staff_members"
- scope:
    path: ''
    type: staff_members
  values:
    _options:
      image_path:
        width: 440
        height: 440
        uploads_dir: "/images/staff_members"
- scope:
    path: ''
  values:
    layout: default
- scope:
    path: ''
    type: posts
  values:
    layout: post
    _options:
      share-img:
        width: 2000
        height: 1322
        resize_style: cover
        uploads_dir: "/images/post_uploads"
      subtitle:
        width: 1500
        height: 2000
        uploads_dir: "/images/post_uploads"
- scope:
    path: contact-success.html
  values:
    layout: page
- scope:
    path: ''
    type: pages
  values:
    image:
      width: 2000
      height: 1322
      resize_style: cover
    bottom_image:
      width: 2000
      height: 1322
      resize_style: cover
url: https://magoanalytics.github.io
baseurl: 
google_analytics_key: 
google_maps_javascript_api_key: 
disqus_shortname: 
logo: "/images/favicon.ico"
description: Magô Analytics is a data consulting collective that aims to empower and
  enable organizations with limited data capabilities
author:
  name: 
  email: 
  twitter: 
social:
  name: Github
  links:
  - https://github.com/magoanalytics
permalink: pretty
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jekyll-paginate
- jekyll-archives
exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENCE
paginate: 10
paginate_path: "/blog/:num/"
jekyll-archives:
  enabled:
  - categories
social_icons:
- Facebook
- Google Plus
- Instagram
- LinkedIn
- Pinterest
- Tumblr
- Twitter
- YouTube
- Email
- RSS
_comments:
  description: Text shown when sharing on social media
  blurb: Short bio or description of this person
